# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - read:user
          #  - read:org
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: santosomar
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_York
          repositories_affiliations: owner, organization_member 
          commits_authoring: santosomar, santosomar@gmail.com, os@cisco.com

          plugin_achievements: yes
          plugin_achievements_display: classic
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          #plugin_code: yes
          #plugin_code_days: 3
          #plugin_code_lines: 12
          #plugin_code_load: 400
          #plugin_code_visibility: public
          plugin_habits: no
#           plugin_habits_from: 1000 
#           plugin_habits_days: 30 
#           plugin_habits_charts: yes
#           plugin_habits_trim: yes  

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: no
#           plugin_languages_analysis_timeout: 15
#           plugin_languages_categories: markup, programming
#           plugin_languages_colors: github
#           plugin_languages_limit: 8
#           plugin_languages_recent_categories: markup, programming
#           plugin_languages_recent_days: 90
#           plugin_languages_recent_load: 300
#           plugin_languages_sections: most-used
#           plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_indepth: yes
          plugin_notable_types: commit
          plugin_sponsors: yes
          plugin_sponsors_sections: goal, about
          plugin_stars: yes
          plugin_stars_limit: 4
